name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:pmoise021/hello-world-python:latest

    - name: Deploy to your server (Optional)
      run: |
        echo "Add deployment steps here"
        - name: Deploy to server
  run: |
    ssh -i ${{ secrets.DEPLOY_KEY }} user@144.126.208.105 << EOF
      docker pull pmoise021/hello-world-python:latest
      docker run -d --name hello-world-app -p 80:8080 pmoise021/hello-world-python:latest
    EOF


